name: "The Cat team scraper"
min_scrape_delay: 0.1 # seconds
max_scrape_delay: 3 # seconds
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
